services:
  book-tracking.api:
    image: book-tracking.api
    build:
      context: .
      dockerfile: BookTracking.Api/Dockerfile
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: localApiUser
      POSTGRES_PASSWORD: localDev
      POSTGRES_DB: book-tracking
      

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"